baseURL = "https://grazielewest.github.io/"
title = "Blog da Graziele"
languageCode = "pt-br"
theme = ""

[params]
  author = "Graziele West"
  description = "Blog sobre tecnologia e desenvolvimento"
  
[menu]
  [[menu.main]]
    name = "ğŸ  Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ğŸ“ Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "â„¹ï¸ Sobre"
    url = "/sobre/"
    weight = 3
